<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="360" /></center>

<center><img src="https://raw.githubusercontent.com/insaid2018/DeepLearning/master/image/keras-logo-2018-large-1200.png" style="width: 600px;"/></center>
                                                                                                           
                                                                                                          

# <center>Keras Assignment</center>

## Table of Content


1. [Linear Regression in Keras](#section1)<br>
2. [Logistic Regression in Keras](#section2)<br>


<a id=section1></a>

## Linear Regression in Keras

### The Boston Housing Price dataset

- You’ll attempt to predict the median price of homes in a given Boston suburb in the mid-1970s, given data points about the suburb at the time, such as the crime rate, the local property tax rate, and so on. 


- The dataset has relatively few data points: only 506, split between 404 training samples and 102 test samples. 


- And each feature in the input data (for example, the crime rate) has a different scale. 
  - For instance, some values are proportions, which take values between 0 and 1; 
  - Others take values between 1 and 12, others between 0 and 100, and so on.

### 1. Loading the Boston housing dataset

In [1]:
# Import tensorflow 2.x
# This code block will only work in Google Colab.
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

In [2]:
import numpy as np

from tensorflow.keras.datasets import boston_housing

In [3]:
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

57344/57026 [==============================] - 0s 0us/step


- Let’s look at the data:

In [4]:
train_data.shape

(404, 13)

In [5]:
test_data.shape

(102, 13)

- As you can see, you have 404 training samples and 102 test samples, each with 13 numerical features, such as per capita crime rate, average number of rooms per dwelling, accessibility to highways, and so on.


- The targets are the median values of owner-occupied homes, in thousands of dollars:

In [6]:
train_targets

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

### 2. Preparing the Data

- Normalizing the data.

In [7]:
mean = train_data.mean(axis=0)

In [8]:
train_data -= mean

In [9]:
std = train_data.std(axis=0)

In [10]:
train_data /= std

In [11]:
test_data -= mean

In [12]:
test_data /= std

### 3. Build the Network

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Question 1: Instantiate a Sequential model.

In [14]:
def init_model():
    model = Sequential() # Instantiate your model here.
    # Dense()
    return model

In [15]:
model = init_model()

#### Question 2: Add layers to the model.

- Add 3 Dense layers to the model.


- 1st layer should contain:
  - **64** hidden units
  - **relu** activation function
  - input shape in the form of a tuple **(num_of_columns_in_train_set,)**


- 2nd layer should contain:
  - **64** hidden units
  - **relu** activation function


- 3rd layer should contain:
  - Hidden units equal to the number of outputs we get at the end of a regression problem i.e. **1**.
  - Use **linear** activation function or don't use activation function at all (this will use the default activation function which is linear).

In [16]:
def build_model(model):
    # Add layers to your model here.
    model.add(Dense(64, activation='relu', input_shape=(train_data.shape[1],)))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1))

    return model

In [17]:
model = build_model(model)

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                896       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 5,121
Trainable params: 5,121
Non-trainable params: 0
_________________________________________________________________


#### Question 3: Compile the model.

- Use **adam** `optimizer`, and **mse** as `loss`.

- Use **mae** in the `metrics` parameter.

In [20]:
def compile_model(model):
    # Compile your model here.
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

In [21]:
model = compile_model(model)

#### Question 4: Fit the Model

- Fit the model with the training data.

- Use **80 number of epochs**, and **batch size of 16** in the `fit` function.

- Don't specify any other hyperparameter.

In [23]:
def fit_model(model):
    # Fit your model here.
    model.fit(train_data, train_targets, epochs=80, batch_size=16)
    return model

In [ ]:
model = fit_model(model)

#### Question 5: Evaluate the Model on the Test data.

- Use the `evaluate` funtion to evaluate the model on the test data.

In [26]:
def evaluate_model(model):
    test_mse_score, test_mae_score = model.evaluate(test_data, test_targets)                   # Evaluate your Model on the Test data here.

    return test_mse_score, test_mae_score

In [27]:
test_mse_score, test_mae_score = evaluate_model(model)

4/4 [==============================] - 0s 2ms/step - loss: 16.1936 - mae: 2.5813


- Here’s the final result on the test dataset:

In [28]:
print('Mean Absolute Error:', test_mae_score)
print('Mean Squared Error:', test_mse_score)

Mean Absolute Error: 2.581256151199341
Mean Squared Error: 16.193605422973633


In [29]:
print('Root Mean Squared Error:', np.sqrt(test_mse_score))

Root Mean Squared Error: 4.024127908376377


## Logistic Regression in Keras

### Titanic Dataset

The goal is to __predict survival__ of passengers travelling in RMS __Titanic__ using __Logistic regression__.

### 1. Loading the Titanic Dataset

In [30]:
import numpy as np
import pandas as pd

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/titanic_train.csv')
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- The dataset consists of the information about people boarding the famous RMS Titanic. Various variables present in the dataset includes data of age, sex, fare, ticket etc. 


- The dataset comprises of __891 observations of 12 columns__. Below is a table showing names of all the columns and their description.

| Column Name   | Description                                               |
| ------------- |:---------------------------------------------------------:| 
| PassengerId   | Passenger Identity                                        | 
| Survived      | Whether passenger survived or not                         |  
| Pclass        | Class of ticket                                           | 
| Name          | Name of passenger                                         |   
| Sex           | Sex of passenger                                          |
| Age           | Age of passenger                                          |
| SibSp         | Number of sibling and/or spouse travelling with passenger |
| Parch         | Number of parent and/or children travelling with passenger|
| Ticket        | Ticket number                                             |
| Fare          | Price of ticket                                           |
| Cabin         | Cabin number                                              |

### 2. Preparing the Data

- Dealing with missing values<br/>
    - Dropping/Replacing missing entries of __Embarked.__
    - Replacing missing values of __Age__ and __Fare__ with median values.
    - Dropping the column __'Cabin'__ as it has too many _null_ values.

In [33]:
df.Embarked = df.Embarked.fillna(df['Embarked'].mode()[0])

In [34]:
median_age = df.Age.median()
median_age

28.0

In [35]:
median_fare = df.Fare.median()
median_fare

14.4542

In [36]:
df.Age.fillna(median_age, inplace = True)
df.Fare.fillna(median_fare, inplace = True)

In [37]:
df.drop('Cabin', axis = 1,inplace = True)

- Creating a new feature named __FamilySize__.

In [38]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.head()

PassengerId  Survived  Pclass  ...     Fare Embarked  FamilySize
0            1         0       3  ...   7.2500        S           2
1            2         1       1  ...  71.2833        C           2
2            3         1       3  ...   7.9250        S           1
3            4         1       1  ...  53.1000        S           2
4            5         0       3  ...   8.0500        S           1

[5 rows x 12 columns]

- Segmenting __Sex__ column as per __Age__, Age less than 15 as __Child__, Age greater than 15 as __Males and Females__ as per their gender.

In [39]:
df['GenderClass'] = df.apply(lambda x: 'child' if x['Age'] < 15 else x['Sex'], axis=1)

In [40]:
df[df.Age < 15].head(2)

PassengerId  Survived  Pclass  ... Embarked FamilySize  GenderClass
7            8         0       3  ...        S          5        child
9           10         1       2  ...        C          2        child

[2 rows x 13 columns]

In [41]:
df[df.Age > 15].head(2)

PassengerId  Survived  Pclass  ... Embarked FamilySize  GenderClass
0            1         0       3  ...        S          2         male
1            2         1       1  ...        C          2       female

[2 rows x 13 columns]

- __Dummification__ of __GenderClass__ & __Embarked__.

In [42]:
df = pd.get_dummies(df, columns=['GenderClass', 'Embarked'], drop_first=True)

- __Dropping__ columns __'Name' , 'Ticket' , 'Sex' , 'SibSp' and 'Parch'__ 

In [43]:
df.drop(['Name','Ticket','Sex','SibSp','Parch'], axis = 1, inplace=True)
df.head()

PassengerId  Survived  Pclass  ...  GenderClass_male  Embarked_Q  Embarked_S
0            1         0       3  ...                 1           0           1
1            2         1       1  ...                 0           0           0
2            3         1       3  ...                 0           0           1
3            4         1       1  ...                 0           0           1
4            5         0       3  ...                 1           0           1

[5 rows x 10 columns]

- Preparing X and y using pandas.

In [44]:
X = df.loc[:, df.columns != 'Survived']
X.head()

PassengerId  Pclass   Age  ...  GenderClass_male  Embarked_Q  Embarked_S
0            1       3  22.0  ...                 1           0           1
1            2       1  38.0  ...                 0           0           0
2            3       3  26.0  ...                 0           0           1
3            4       1  35.0  ...                 0           0           1
4            5       3  35.0  ...                 1           0           1

[5 rows x 9 columns]

In [45]:
y = df.Survived
y[:10]

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

- Splitting the dataset into train and test sets.

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [48]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(712, 9)
(712,)
(179, 9)
(179,)


### 3. Build the Network

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Question 6: Instantiate a Sequential model.

In [50]:
def init_model():
    model = Sequential() # Instantiate your model here.

    return model

In [51]:
model = init_model()

#### Question 7: Add layers to the model.

- Add 3 Dense layers to the model.


- 1st layer should contain:
  - **64** hidden units
  - **relu** activation function
  - input shape in the form of a tuple **(num_of_columns_in_train_set,)**


- 2nd layer should contain:
  - **64** hidden units
  - **relu** activation function


- 3rd layer should contain:
  - Hidden units equal to the number of outputs we get at the end of a binary classification problem i.e. **1**.
  - Use **sigmoid** activation function (**sigmoid** activation function is used in **binary** classification problems in the last layer).

In [55]:
def build_model(model):
    # Add layers to your model here.
    
    model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    return model

In [59]:
model = build_model(model)

In [60]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                640       
_________________________________________________________________
dense_4 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
_________________________________________________________________
dense_6 (Dense)              (None, 64)                128       
_________________________________________________________________
dense_7 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 65        
Total params: 9,218
Trainable params: 9,218
Non-trainable params: 0
____________________________________________________

#### Question 8: Compile the model.

- Use **adam** `optimizer`, and **binary_crossentropy** as `loss`.

- Use **accuracy** in the `metrics` parameter.

In [61]:
def compile_model(model):
    # Compile your model here.
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')
    return model

In [62]:
model = compile_model(model)

#### Question 9: Fit the Model

- Fit the model with the training data.

- Use **100 number of epochs**, and **batch size of 16** in the `fit` function.

- Don't specify any other hyperparameter.

In [63]:
def fit_model(model):
    history = model.fit(X_train, y_train, epochs=100, batch_size=16)
    # Fit your model here.

    return model, history

In [64]:
model, history = fit_model(model)

Epoch 1/100
45/45 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.6222
Epoch 2/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6647 - accuracy: 0.6222
Epoch 3/100
45/45 [==============================] - 0s 2ms/step - loss: 0.6646 - accuracy: 0.6222
Epoch 4/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6637 - accuracy: 0.6222
Epoch 5/100
45/45 [==============================] - 0s 2ms/step - loss: 0.6722 - accuracy: 0.6222
Epoch 6/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6689 - accuracy: 0.6222
Epoch 7/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6642 - accuracy: 0.6222
Epoch 8/100
45/45 [==============================] - 0s 2ms/step - loss: 0.6634 - accuracy: 0.6222
Epoch 9/100
45/45 [==============================] - 0s 2ms/step - loss: 0.6635 - accuracy: 0.6222
Epoch 10/100
45/45 [==============================] - 0s 3ms/step - loss: 0.6631 - accuracy: 0.6222
Epoch 11/

#### Question 10: Evaluate the Model on the Test data.

- Use the `evaluate` funtion to evaluate the model on the test data.

In [65]:
def evaluate_model(model):
    loss, accuracy = model.evaluate(X_test, y_test)
    # Evaluate your Model on the Test data here.

    return loss, accuracy

In [66]:
loss, accuracy = evaluate_model(model)

6/6 [==============================] - 0s 2ms/step - loss: 0.6984 - accuracy: 0.5922


- Here’s the final result:

In [67]:
print('Accuracy:', accuracy)

Accuracy: 0.5921787619590759
