<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="360" /></center>

<center><img src="https://raw.githubusercontent.com/insaid2018/DeepLearning/master/image/keras-logo-2018-large-1200.png" style="width: 600px;"/></center>
                                                                                                           
                                                                                                          

# <center>Keras Assignment</center>

## Table of Content


1. [Linear Regression in Keras](#section1)<br>
2. [Logistic Regression in Keras](#section2)<br>


<a id=section1></a>

## Linear Regression in Keras

### The Boston Housing Price dataset

- You’ll attempt to predict the median price of homes in a given Boston suburb in the mid-1970s, given data points about the suburb at the time, such as the crime rate, the local property tax rate, and so on. 


- The dataset has relatively few data points: only 506, split between 404 training samples and 102 test samples. 


- And each feature in the input data (for example, the crime rate) has a different scale. 
  - For instance, some values are proportions, which take values between 0 and 1; 
  - Others take values between 1 and 12, others between 0 and 100, and so on.

### 1. Loading the Boston housing dataset

In [0]:
# Import tensorflow 2.x
# This code block will only work in Google Colab.
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

TensorFlow 2.x selected.


In [0]:
import numpy as np

from tensorflow.keras.datasets import boston_housing

In [0]:
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

- Let’s look at the data:

In [0]:
train_data.shape

(404, 13)

In [0]:
test_data.shape

(102, 13)

- As you can see, you have 404 training samples and 102 test samples, each with 13 numerical features, such as per capita crime rate, average number of rooms per dwelling, accessibility to highways, and so on.


- The targets are the median values of owner-occupied homes, in thousands of dollars:

In [0]:
train_targets

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

### 2. Preparing the Data

- Normalizing the data.

In [0]:
mean = train_data.mean(axis=0)

In [0]:
train_data -= mean

In [0]:
std = train_data.std(axis=0)

In [0]:
train_data /= std

In [0]:
test_data -= mean

In [0]:
test_data /= std

### 3. Build the Network

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Question 1: Instantiate a Sequential model.

In [0]:
def init_model():
    model = Sequential()

    return model

In [0]:
model = init_model()

#### Question 2: Add layers to the model.

- Add 3 Dense layers to the model.


- 1st layer should contain:
  - **64** hidden units
  - **relu** activation function
  - input shape in the form of a tuple **(num_of_columns_in_train_set,)**


- 2nd layer should contain:
  - **64** hidden units
  - **relu** activation function


- 3rd layer should contain:
  - Hidden units equal to the number of outputs we get at the end of a regression problem i.e. **1**.
  - Use **linear** activation function or don't use activation function at all (this will use the default activation function which is linear).

In [0]:
def build_model(model):
    model.add(Dense(64, activation='relu', input_shape=(train_data.shape[1],)))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1))

    return model

In [0]:
model = build_model(model)

In [0]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                896       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65        
Total params: 5,121
Trainable params: 5,121
Non-trainable params: 0
_________________________________________________________________


#### Question 3: Compile the model.

- Use **adam** `optimizer`, and **mse** as `loss`.

- Use **mae** in the `metrics` parameter.

In [0]:
def compile_model(model):
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])

    return model

In [0]:
model = compile_model(model)

#### Question 4: Train the Model

- Fit the model with the training data.

- Use **80 number of epochs**, and **batch size of 16** in the `fit` function.

- Don't specify any other hyperparameter.

In [0]:
def fit_model(model):
    model.fit(train_data, train_targets, epochs=80, batch_size=16)

    return model

In [0]:
model = fit_model(model)

404/404 [==============================] - 5s 12ms/step - loss: 537.3262 - mean_absolute_error: 21.2841
Epoch 2/80
404/404 [==============================] - 0s 254us/step - loss: 403.6577 - mean_absolute_error: 17.8909
Epoch 3/80
404/404 [==============================] - 0s 244us/step - loss: 223.0374 - mean_absolute_error: 12.3661
Epoch 4/80
404/404 [==============================] - 0s 275us/step - loss: 77.6162 - mean_absolute_error: 6.5511
Epoch 5/80
404/404 [==============================] - 0s 243us/step - loss: 40.8368 - mean_absolute_error: 4.5436
Epoch 6/80
404/404 [==============================] - 0s 254us/step - loss: 29.3845 - mean_absolute_error: 3.8004
Epoch 7/80
404/404 [==============================] - 0s 239us/step - loss: 24.1147 - mean_absolute_error: 3.4307
Epoch 8/80
404/404 [==============================] - 0s 249us/step - loss: 21.2679 - mean_absolute_error: 3.2410
Epoch 9/80
404/404 [==============================] - 0s 244us/step - loss: 19.5333 - mean_abs

#### Question 5: Evaluate the Model on the Test data.

- Use the `evaluate` funtion to evaluate the model on the test data.

In [0]:
def evaluate_model(model):
    test_mse_score, test_mae_score = model.evaluate(test_data, test_targets)

    return test_mse_score, test_mae_score

In [0]:
test_mse_score, test_mae_score = evaluate_model(model)

102/102 [==============================] - 0s 370us/step


- Here’s the final result on the test dataset:

In [0]:
print('Mean Absolute Error:', test_mae_score)
print('Mean Squared Error:', test_mse_score)

Mean Absolute Error: 2.6399879549063887
Mean Squared Error: 17.82345132266774


In [0]:
print('Root Mean Squared Error:', np.sqrt(test_mse_score))

Root Mean Squared Error: 4.22178295541916


## Logistic Regression in Keras

### Titanic Dataset

The goal is to __predict survival__ of passengers travelling in RMS __Titanic__ using __Logistic regression__.

### 1. Loading the Titanic Dataset

In [0]:
import numpy as np
import pandas as pd

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/titanic_train.csv')
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- The dataset consists of the information about people boarding the famous RMS Titanic. Various variables present in the dataset includes data of age, sex, fare, ticket etc. 


- The dataset comprises of __891 observations of 12 columns__. Below is a table showing names of all the columns and their description.

| Column Name   | Description                                               |
| ------------- |:---------------------------------------------------------:| 
| PassengerId   | Passenger Identity                                        | 
| Survived      | Whether passenger survived or not                         |  
| Pclass        | Class of ticket                                           | 
| Name          | Name of passenger                                         |   
| Sex           | Sex of passenger                                          |
| Age           | Age of passenger                                          |
| SibSp         | Number of sibling and/or spouse travelling with passenger |
| Parch         | Number of parent and/or children travelling with passenger|
| Ticket        | Ticket number                                             |
| Fare          | Price of ticket                                           |
| Cabin         | Cabin number                                              |

### 2. Preparing the Data

- Dealing with missing values<br/>
    - Dropping/Replacing missing entries of __Embarked.__
    - Replacing missing values of __Age__ and __Fare__ with median values.
    - Dropping the column __'Cabin'__ as it has too many _null_ values.

In [0]:
df.Embarked = df.Embarked.fillna(df['Embarked'].mode()[0])

In [0]:
median_age = df.Age.median()
median_age

28.0

In [0]:
median_fare = df.Fare.median()
median_fare

14.4542

In [0]:
df.Age.fillna(median_age, inplace = True)
df.Fare.fillna(median_fare, inplace = True)

In [0]:
df.drop('Cabin', axis = 1,inplace = True)

- Creating a new feature named __FamilySize__.

In [0]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.head()

PassengerId  Survived  Pclass  ...     Fare Embarked  FamilySize
0            1         0       3  ...   7.2500        S           2
1            2         1       1  ...  71.2833        C           2
2            3         1       3  ...   7.9250        S           1
3            4         1       1  ...  53.1000        S           2
4            5         0       3  ...   8.0500        S           1

[5 rows x 12 columns]

- Segmenting __Sex__ column as per __Age__, Age less than 15 as __Child__, Age greater than 15 as __Males and Females__ as per their gender.

In [0]:
df['GenderClass'] = df.apply(lambda x: 'child' if x['Age'] < 15 else x['Sex'], axis=1)

In [0]:
df[df.Age < 15].head(2)

PassengerId  Survived  Pclass  ... Embarked FamilySize  GenderClass
7            8         0       3  ...        S          5        child
9           10         1       2  ...        C          2        child

[2 rows x 13 columns]

In [0]:
df[df.Age > 15].head(2)

PassengerId  Survived  Pclass  ... Embarked FamilySize  GenderClass
0            1         0       3  ...        S          2         male
1            2         1       1  ...        C          2       female

[2 rows x 13 columns]

- __Dummification__ of __GenderClass__ & __Embarked__.

In [0]:
df = pd.get_dummies(df, columns=['GenderClass', 'Embarked'], drop_first=True)

- __Dropping__ columns __'Name' , 'Ticket' , 'Sex' , 'SibSp' and 'Parch'__ 

In [0]:
df.drop(['Name','Ticket','Sex','SibSp','Parch'], axis = 1, inplace=True)
df.head()

PassengerId  Survived  Pclass  ...  GenderClass_male  Embarked_Q  Embarked_S
0            1         0       3  ...                 1           0           1
1            2         1       1  ...                 0           0           0
2            3         1       3  ...                 0           0           1
3            4         1       1  ...                 0           0           1
4            5         0       3  ...                 1           0           1

[5 rows x 10 columns]

- Preparing X and y using pandas.

In [0]:
X = df.loc[:, df.columns != 'Survived']
X.head()

PassengerId  Pclass   Age  ...  GenderClass_male  Embarked_Q  Embarked_S
0            1       3  22.0  ...                 1           0           1
1            2       1  38.0  ...                 0           0           0
2            3       3  26.0  ...                 0           0           1
3            4       1  35.0  ...                 0           0           1
4            5       3  35.0  ...                 1           0           1

[5 rows x 9 columns]

In [0]:
y = df.Survived
y[:10]

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

- Splitting the dataset into train and test sets.

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [0]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(712, 9)
(712,)
(179, 9)
(179,)


### 3. Build the Network

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Question 6: Instantiate a Sequential model.

In [0]:
def init_model():
    model = Sequential()

    return model

In [0]:
model = init_model()

#### Question 7: Add layers to the model.

- Add 3 Dense layers to the model.


- 1st layer should contain:
  - **64** hidden units
  - **relu** activation function
  - input shape in the form of a tuple **(num_of_columns_in_train_set,)**


- 2nd layer should contain:
  - **64** hidden units
  - **relu** activation function


- 3rd layer should contain:
  - Hidden units equal to the number of outputs we get at the end of a binary classification problem i.e. **1**.
  - Use **sigmoid** activation function (**sigmoid** activation function is used in **binary** classification problems in the last layer).

In [0]:
def build_model(model):
    model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    return model

In [0]:
model = build_model(model)

In [0]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                640       
_________________________________________________________________
dense_5 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 65        
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


#### Question 8: Compile the model.

- Use **adam** `optimizer`, and **binary_crossentropy** as `loss`.

- Use **accuracy** in the `metrics` parameter.

In [0]:
def compile_model(model):
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

In [0]:
model = compile_model(model)

#### Question 9: Train the Model

- Fit the model with the training data.

- Use **100 number of epochs**, and **batch size of 16** in the `fit` function.

- Don't specify any other hyperparameter.

In [0]:
def fit_model(model):
    history = model.fit(X_train, y_train, epochs=100, batch_size=16)

    return model, history

In [0]:
model, history = fit_model(model)

Epoch 1/100
712/712 [==============================] - 1s 765us/step - loss: 1.2492 - acc: 0.6180
Epoch 2/100
712/712 [==============================] - 0s 283us/step - loss: 0.8302 - acc: 0.6222
Epoch 3/100
712/712 [==============================] - 0s 286us/step - loss: 0.8228 - acc: 0.6601
Epoch 4/100
712/712 [==============================] - 0s 291us/step - loss: 0.7275 - acc: 0.6742
Epoch 5/100
712/712 [==============================] - 0s 283us/step - loss: 0.7161 - acc: 0.6699
Epoch 6/100
712/712 [==============================] - 0s 289us/step - loss: 0.7372 - acc: 0.6531
Epoch 7/100
712/712 [==============================] - 0s 302us/step - loss: 0.7119 - acc: 0.7205
Epoch 8/100
712/712 [==============================] - 0s 329us/step - loss: 0.5843 - acc: 0.7135
Epoch 9/100
712/712 [==============================] - 0s 301us/step - loss: 0.5761 - acc: 0.7289
Epoch 10/100
712/712 [==============================] - 0s 277us/step - loss: 0.5258 - acc: 0.7584
Epoch 11/100
712/71

#### Question 10: Evaluate the Model on the Test data.

- Use the `evaluate` funtion to evaluate the model on the test data.

In [0]:
def evaluate_model(model):
    loss, accuracy = model.evaluate(X_test, y_test)

    return loss, accuracy

In [0]:
loss, accuracy = evaluate_model(model)

179/179 [==============================] - 0s 343us/step


- Here’s the final result:

In [0]:
print('Accuracy:', accuracy)

Accuracy: 0.7653631274926596
